# Generated by Django 4.2 on 2023-06-10 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0002_mahsulot_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahsulot',
            name='chegirma',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mahsulot',
            name='min_miqdor',
            field=models.SmallIntegerField(default=1),
        ),
    ]
