# Generated by Django 4.2 on 2023-06-13 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0004_alter_media_rasm'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahsulot',
            name='mavjud',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mahsulot',
            name='yetkazish',
            field=models.CharField(default='3 kun', max_length=20),
            preserve_default=False,
        ),
    ]
