# Generated by Django 4.2 on 2023-06-20 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_accaunt_delete_foydalanuvchi'),
        ('buyurtma', '0002_savat_rename_account_tanlangan_accaunt_savatitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savat',
            name='holat',
            field=models.CharField(choices=[('buyurtma qlindi', 'buyurtma qlindi'), ('buyurtma qlinmadi', 'buyurtma qlinmadi')], max_length=30),
        ),
        migrations.CreateModel(
            name='Manzil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('davlat', models.CharField(max_length=50)),
                ('shahar', models.CharField(max_length=50)),
                ('zipcode', models.CharField(max_length=50)),
                ('manzil', models.CharField(max_length=200)),
                ('asosiy', models.BooleanField(default=True)),
                ('accaunt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.accaunt')),
            ],
        ),
        migrations.CreateModel(
            name='Buyurtma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sana', models.DateField(auto_now_add=True)),
                ('holat', models.CharField(max_length=50)),
                ('accaunt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.accaunt')),
                ('manzil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyurtma.manzil')),
                ('savat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyurtma.savat')),
            ],
        ),
    ]
