# Generated by Django 4.2 on 2023-06-20 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buyurtma', '0003_alter_savat_holat_manzil_buyurtma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savatitem',
            name='savat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itemlari', to='buyurtma.savat'),
        ),
    ]
